resources:
  - name: py-script
    type: git
    source:
      uri: "https://github.com/rahu1acharya/concourse.git"
      branch: main

jobs:
  - name: fetch-secrets
    plan:
      - get: py-script
      - task: fetch-secrets-task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: vault
              tag: "1.13.3"
          inputs:
            - name: py-script
          outputs:
            - name: secrets-output
          run:
            path: sh
            args:
              - -c
              - |
                # Set Vault address and token
                VAULT_ADDR="http://192.168.56.1:8200"
                VAULT_TOKEN="rahul"

                export VAULT_ADDR
                export VAULT_TOKEN

                username=$(vault kv get -field=username secret/cred)
                password=$(vault kv get -field=password secret/cred)
                
                echo "USERNAME=$username" > secrets-output/secrets.env
                echo "PASSWORD=$password" >> secrets-output/secrets.env
                chmod 600 secrets-output/secrets.env
                
                # Debugging: List the contents of the secrets directory
                echo "Contents of secrets-output directory:"
                ls -l secrets-output
                
                # Debugging: Print the contents of the secrets file
                echo "Contents of secrets.env:"
                cat secrets-output/secrets.env

      - task: run-scrape-task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: "3.9"  # or any other version you need
          inputs:
            - name: py-script
            - name: secrets-output
          outputs:
            - name: scraped-data
          run:
            path: sh
            args:
              - -c
              - |
                # Install dependencies
                pip install requests beautifulsoup4 pandas sqlalchemy psycopg2-binary
                echo "Contents of secrets.env:"
                cat secrets-output/secrets.env
                set -a
                . secrets-output/secrets.env
                set +a
 
                # Navigate to the directory containing scrape.py
                cd py-script
                
                # Run the scrape.py script
                python scrape.py

                mv reliance_data.csv ../scraped-data/

                # Print the contents of the CSV file
                echo "Contents of reliance_data.csv in scraped-data directory:"
                cat ../scraped-data/reliance_data.csv
